package com.root.commondependencies;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class CommonDependenciesApplication {

	public static void main(String[] args) {
		SpringApplication.run(CommonDependenciesApplication.class, args);
	}

}
